### ISSUE TITLE
TestR2LVersusSage go test sometimes fails on armhf architecture

### ISSUE THREAD

**Issue by rogers0** [cloudflarearchive/sidh#29]
https://tests.reproducible-builds.org/debian/logs/bullseye/armhf/golang-github-cloudflare-sidh_1.0+git20190228.d2f0f90-4.build2.log.gz

error log:
```
=== RUN   TestR2LVersusSage
panic: test timed out after 10m0s

goroutine 24 [running]:
testing.(*M).startAlarm.func1()
	/usr/lib/go-1.14/src/testing/testing.go:1459 +0xbc
created by time.goFunc
	/usr/lib/go-1.14/src/time/sleep.go:168 +0x34

goroutine 1 [chan receive]:
testing.(*T).Run(0x24d46e0, 0x19dce4, 0x11, 0x1a6d04, 0x301)
	/usr/lib/go-1.14/src/testing/testing.go:1043 +0x2d0
testing.runTests.func1(0x24d4000)
	/usr/lib/go-1.14/src/testing/testing.go:1284 +0x68
testing.tRunner(0x24d4000, 0x24306f8)
	/usr/lib/go-1.14/src/testing/testing.go:991 +0xbc
testing.runTests(0x2496040, 0x2c5e68, 0x17, 0x17, 0x0)
	/usr/lib/go-1.14/src/testing/testing.go:1282 +0x238
testing.(*M).Run(0x2498100, 0x0)
	/usr/lib/go-1.14/src/testing/testing.go:1199 +0x134
main.main()
	_testmain.go:122 +0x120

goroutine 67 [runnable]:
github.com/cloudflare/sidh/p751.fp751Mul(0x2492940, 0x2493224, 0x2493224)
	/build/golang-github-cloudflare-sidh-1.0+git20190228.d2f0f90/obj-arm-linux-gnueabihf/src/github.com/cloudflare/sidh/p751/arith_generic.go:145 +0x250
github.com/cloudflare/sidh/p751.(*primeFieldElement).Mul(0x2493224, 0x2493224, 0x2493224, 0x2493224)
	/build/golang-github-cloudflare-sidh-1.0+git20190228.d2f0f90/obj-arm-linux-gnueabihf/src/github.com/cloudflare/sidh/p751/field_ops.go:196 +0x44
github.com/cloudflare/sidh/p751.(*primeFieldElement).Pow2k(0x2493224, 0x2493224, 0x2493105, 0x2493224)
	/build/golang-github-cloudflare-sidh-1.0+git20190228.d2f0f90/obj-arm-linux-gnueabihf/src/github.com/cloudflare/sidh/p751/field_ops.go:210 +0x48
github.com/cloudflare/sidh/p751.(*primeFieldElement).P34(0x2493224, 0x2493224, 0x2493284)
	/build/golang-github-cloudflare-sidh-1.0+git20190228.d2f0f90/obj-arm-linux-gnueabihf/src/github.com/cloudflare/sidh/p751/field_ops.go:249 +0x170
github.com/cloudflare/sidh/p751.fp751Ops.Inv(0x27c1140, 0x27c1140)
	/build/golang-github-cloudflare-sidh-1.0+git20190228.d2f0f90/obj-arm-linux-gnueabihf/src/github.com/cloudflare/sidh/p751/field_ops.go:117 +0xcc
github.com/cloudflare/sidh/internal/isogeny.(*CurveOperations).CalcAplus2Over4(0x2c3048, 0x2b5998, 0xc7f1c937, 0xebdc7e9e, 0x882d9075, 0xfa46b5e0, 0x63e112a8, 0x693d8a93, 0x7c122a7e, 0x6d41e589, ...)
	/build/golang-github-cloudflare-sidh-1.0+git20190228.d2f0f90/obj-arm-linux-gnueabihf/src/github.com/cloudflare/sidh/internal/isogeny/curve_ops.go:95 +0xe0
github.com/cloudflare/sidh/internal/isogeny.(*CurveOperations).ScalarMul3Pt(0x2c3048, 0x2b5998, 0x2bcd58, 0x2bced8, 0x2bd058, 0x100, 0x2b0f50, 0x20, 0x20, 0x0, ...)
	/build/golang-github-cloudflare-sidh-1.0+git20190228.d2f0f90/obj-arm-linux-gnueabihf/src/github.com/cloudflare/sidh/internal/isogeny/curve_ops.go:238 +0xa0
github.com/cloudflare/sidh/p751.TestR2LVersusSage(0x24d46e0)
	/build/golang-github-cloudflare-sidh-1.0+git20190228.d2f0f90/obj-arm-linux-gnueabihf/src/github.com/cloudflare/sidh/p751/curve_test.go:151 +0x228
testing.tRunner(0x24d46e0, 0x1a6d04)
	/usr/lib/go-1.14/src/testing/testing.go:991 +0xbc
created by testing.(*T).Run
	/usr/lib/go-1.14/src/testing/testing.go:1042 +0x2b0
FAIL	github.com/cloudflare/sidh/p751	600.232s
```

**Comment by Bren2010** [comment]
I believe this repo is outdated and the code has been moved here:
https://github.com/cloudflare/circl/tree/master/dh/sidh
Perhaps check if that code has the same issue and open a ticket there if so?

**Comment by rogers0** [comment]
understood. thanks for your guide!
